import os
from .constants import ModelName

# One seed to rule them all
SEED_CONSTANT = 28 # This is how old I was when I started this project. Also it is good to have a constant seed for reproducibility.

PROJECT_DIR = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
MODELS_DIR = os.path.join(PROJECT_DIR, 'processed_models')
DATASETS_DIR =  os.path.join(PROJECT_DIR, 'datasets')
DATASET_NAME = 'UCF-101'
PREPROCESSED_IMAGES_NAME = 'preprocessed_images'
PREPROCESSED_IMAGES_DIR = os.path.join(DATASETS_DIR, PREPROCESSED_IMAGES_NAME)
MODEL_FORMAT = 'h5'

DEFAULT_MODEL_NAME = ModelName.LRCN

IMAGE_HEIGHT, IMAGE_WIDTH = 64, 64
FRAMES_COUNT = 20
BATCH_SIZE = 128
EPOCHS_COUNT = 5

# The section for testing scripts
DEFAULT_TRAINED_MODEL_NAME = 'lrcn_model_20231115213346_5_0.107'
DEFAULT_YT_VIDEO_URL = 'https://www.youtube.com/watch?v=ZVUyyHYkBHk' # The video is generated by GitHub Copilot so no blame for me here.
TEST_VIDEOS_DIRECTORY = os.path.join(PROJECT_DIR, 'test_videos')